{
      "bahasa": "Please select a language to see the list of languages, please press the button below",
      "maxtext": "Maximum 150 texts brother",
      "sukses1": "Success, I have conveyed your message to the owner",
      "sukses2": "broadcast success",
      "sukses3": "success",   
      "replybiasater": "Hehhh.. As usual... the",
      "replyin": "Here",      
      "terreply": "So it's like this bro, I'm the one who's the most",
      "notfitur": "seems not listed in the bot menu, please check the menu again :)",
      "respon": "Yah brother? I'm here, can I help you?",
      "botadmin": "sorry this feature can only be used if the bot is an admin",
      "group": "sorry this feature can only be used in groups",
      "admin": "sorry this feature can only be used by group admins",
      "owner": "sorry this feature can only be used by owner bot",
      "member": "sorry this feature can only be used by group members",
      "pribadi": "sorry this feature can only be used for private orders",
      "premium": "sorry this feature can only be used by premium users",
      "linkerror": "The link you submitted is error",
      "nolink": "Enter grub link",
      "reptag": "Tag someone bro :)",      
      "banned": "Sorry but you have been banned :(",
      "fakeaudio": "Here's the audio bro :)",
      "nonumber": "Enter the number, note: don't put a space/code(+-) in the number",
      "nocode": "Enter country code",
      "timetag": "Your message will be sent on",
      "kikrndm": "Looking for random members in this group",
      "noprefix": "Enter a new prefix, maximum 1 number/letter",
      "notext": "Enter the text bro"
}